### ISSUE TITLE
Add possibility to manage the order of pictures in the Library

### ISSUE THREAD

**Issue by Quimoune** [CLOXnu/ConvenientImagePicker#5]
Great thanks for this lib !
If you can just put the ordering option on public. Here what I need to do because "modificationDate" is not good for me.

```
**PickerViewController.swift**
l. 56    /// A String value that determines whether the order key of all assets.
l. 57    public var assetsSortKey = "modificationDate"
l. 58    /// A Boolean value that determines whether the order way of all assets.
l. 59    public var assetsSortAscending = false
```

And :
```
**PickerViewDataSource.swift**
l. 138         allPhotosOptions.sortDescriptors = [NSSortDescriptor(key: self.assetsSortKey, ascending: self.assetsSortAscending)]

```

That would be really great !

Thanks,
Kind regards.

Édouard.

**Comment by cloxnu** [comment]
OK, the new version is coming, pull request is also welcome.
thanks @quimoune

**Comment by Quimoune** [comment]
> OK, the new version is coming, pull request is also welcome.
> thanks @quimoune

Ok, just did one !
Thanks !
